### ISSUE TITLE
Moving file with example terminal commandfails

### ISSUE THREAD

**Issue by jclarkv** [evadogstar/qvm-screenshot-tool#1]
After downloading the tool to my 'personal' vm I typed the following into my dom0 terminal window:

qvm-run --pass-io personal 'cat /path/to/qvm-screenshot-tool.sh' > /home/user/Pictures/qvm-screenshot-tool.sh

response:
bash: /home/user/Pictures/qvm-screenshot-tool.sh: No such file or directory

This is on a new Qubes 3.1 installation with all vm templates updated.
I'm new to linux, so I'm sure the problem is with my interpretation of the provided CLI command.

**Comment by evadogstar** [comment]
@jclarkv 
1) Check where you place `qvm-screenshot-tool.sh` at personal AppVM. try to place it at the user home: /home/user/qvm-screenshot-tool.sh
2) then check Pictures directory exists at the dom0

qvm-run --pass-io personal 'cat /home/user/qvm-screenshot-tool.sh' > /home/user/Pictures/qvm-screenshot-tool.sh
or
qvm-run --pass-io personal 'cat /home/user/qvm-screenshot-tool.sh' > /home/user/qvm-screenshot-tool.sh
(last command to store it at the home of dom0 user)

**Comment by jclarkv** [comment]
Run those command in dom0 terminal or personal terminal?

**Comment by evadogstar** [comment]
@jclarkv on dom0 terminal.
