### ISSUE TITLE
Add flag support

### ISSUE THREAD

**Issue by anoadragon453** [evadogstar/qvm-screenshot-tool#2]
First of all, thank you for this tool, it's a huge time saver!

I have a suggestion for further time-saving though. When using this tool, I often just select 'Region or Window' in the first menu. Doing this each time is a bit tedious. Would it be possible to add some flags like `-r` and `--region-only` so that we can skip the first menu and start taking a screenshot immediately?

Thanks!

**Comment by evadogstar** [comment]
@anoadragon453 Done. Now flags available: `--region-only` and `--fullscreen`

**Comment by anoadragon453** [comment]
Thanks!

It works great from the command line, only problem is that binding it (at least within i3) doesn't seem to work as scrot will detect a key is being held down (as part of the binding) and immediately exit with the following error:

```
[+] capturing window, click on it to select
Key was pressed, aborting shot
giblib error: no image grabbed
```

As far as I can tell `scrot` will not take any flags that prevent this behavior. `xfce4-screenshooter` on the other hand does not have this limitation and actually works quite well in a scripted environment. It also seems that it is installed by default in Qubes' dom0. Perhaps adding it as an additional (or replacement) backend may be a good idea?

I also occasionally get some issues with `scrot`'s bounding boxes appearing in the screenshot as well, an issue which `xfce4-screenshooter` does not seem to have.

**Comment by anoadragon453** [comment]
Anyways, you've added flag support so I'll close this issue and perhaps open a PR for `xfce4-screenshooter` in the near future :)
